additional lineplot works
VEuPathDB/web-eda pull request #1007
Opened 2022-03-31 02:44 UTC by moontrip

This will probably rely on https://github.com/VEuPathDB/web-components/pull/333
This PR will be used for addressing additional lineplot works. Thus branched out from `lineplot-categorical` branch.

2022-03-31 02:46 UTC, moontrip commented
As a first commit, #1003 for lineplot Viz was addressed here. 
Next, axis range control will be implemented here.

2022-04-02 22:10 UTC, moontrip commented
@bobular I have done several works for lineplot Viz. This branch/PR is up-to-date to `main` branch but for now, it is supposed to be merged into your branch, `lineplot-categorical`. I think that this PR may be used for UX discussion on Monday if they want to discuss lineplot - last week they cancelled it due to your vacation. FYI, I am out of VEuPathDB on Monday but may check email and slack, if not on time.

This PR contains several updates and relies on [web-components PR](https://github.com/VEuPathDB/web-components/pull/333) (please use yarn link):

- axis range control is now working: see the second and third screenshots below.
- I think that we can't support X-axis range control for categorical variable, so I introduced a new prop, `disabled`, for both (number/date) input form and (reset) button (via web-components' control and widgets) to disable. For that case, I also added to show text at title, like `Range (not available)`. Please see the first screenshot.
- The bug you found, switching number to date variable or vice versa (#1003) is also addressed
- For your information, I have made two methods for initial Y-axis range/viewport: Method 1 - considering variable's metadata for min/max; Method 2 - purely based on data min/max, which may be in line with Danica's thought. I left comment so you can test both by commenting out each of them: currently Method 1 is used (Method 2 is commented out)


### Screenshots
- categorical X-axis variable (X-axis range is disabled)
![lineplot-xCategorical](https://user-images.githubusercontent.com/12802305/161402877-d949bd7b-3577-4693-b3f0-419434b3b8a5.png)

- axis range controls and truncations for number variables
![lineplot-truncations-numbers](https://user-images.githubusercontent.com/12802305/161402892-f28cbf3c-cfe9-4235-bcd6-84485330c059.png)

- axis range controls and truncations for date variables
![lineplot-truncations-dates](https://user-images.githubusercontent.com/12802305/161402908-5e7ba1eb-320e-4837-9d3a-1cc403eb35d6.png)

2022-04-04 10:27 UTC, bobular requested changes
Axis controls work great and code looks good.

Please take a look at the scatterplot number-to-date variable bug that still remains.

2022-04-04 10:51 UTC, bobular commented on src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
> +      : // add conditions to prevent previous yMinMaxRange from calling the function, e.g., date to categorical
PS. I haven't tested the alternatives for y-axis range calculations. We can wait for UX meeting feedback.

PPS. I did test the disabling of x axis range controls when ordinal (e.g. "age group") variables are used and that works great.

2022-04-04 11:00 UTC, bobular commented on src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
> +      : // add conditions to prevent previous yMinMaxRange from calling the function, e.g., date to categorical
Oh, I see scatterplot is fixed in https://github.com/VEuPathDB/web-eda/pull/1004

2022-04-04 11:43 UTC, bobular commented
I made the viewport part of the data request use the `independentAxisRange`

It works fine, but every time the first marker is cut in half by the yellow warning shading.  Not sure of the best solution.
![image](https://user-images.githubusercontent.com/308639/161536689-938939d1-b7c2-43fe-b706-21303dea358b.png)

2022-04-04 12:54 UTC, moontrip commented
@bobular I hope you enjoyed your relatively long vacation 😄 
And thank you for your reviews on my several PRs 👍 I am pleased that most of them worked fine. Yes scatter plot bug on the switch of number to date variable (or vice versa) was addressed in the separate PR. Speaking of your suggestion on the combined condition at axisRangeMargin() for both scatterplot and lineplot Vizs, I thought of it but didn't do that because lineplot Viz required one additional check condition for ordinal/categorical case.  

And thank you for adding the viewport feature for lineplot 👍: I was not sure if I should have made it for lineplot. Yes, I also noticed that the error bar often cut in half depending on the range input value but I did/do not have clear answer to address it either 🤔 Maybe it is acceptable? 😉

2022-04-05 12:57 UTC, bobular commented
Danica and others said the cut in half points/error bars wasn't a show stopper yesterday.

2022-04-05 12:57 UTC, bobular approved these changes

2022-04-05 12:57 UTC, merged