Add barebones fullscreen map
VEuPathDB/web-eda pull request #1315
Opened 2022-08-12 17:54 UTC by chowington

Fixes https://github.com/VEuPathDB/web-eda/issues/1307

2022-08-15 18:09 UTC, bobular requested changes
This is great, but we need to figure out where to merge it to. It can't be `main` unless somehow the "open fullscreen map" button is easily hidden.

We could just keep a branch going to merge FSM tickets into, and keep merging from main to make the final merge back to main relatively pain free?

2022-08-15 18:09 UTC, bobular commented on src/lib/workspace/WorkspaceRouter.tsx
> +            ]}
Could this multiple path matching be used to DRY up the regular analysis routes? (`:analysisId` and `new`)

2022-08-15 19:20 UTC, dmfalke commented
> This is great, but we need to figure out where to merge it to. It can't be `main` unless somehow the "open fullscreen map" button is easily hidden.
> 
> We could just keep a branch going to merge FSM tickets into, and keep merging from main to make the final merge back to main relatively pain free?

This is a good use case for a feature flag. We don't have specific infrastructure for feature flags, but it wouldn't be too hard to add something.

2022-08-15 19:24 UTC, dmfalke commented on src/lib/mapveu/MapVEuFullscreen.tsx
> +        if (event.key === 'Escape') history.goBack();
It's likely that your focus is still on the button that opened the map. Maybe when the map opens, we can change the focus to the map div?

2022-09-09 21:08 UTC, chowington commented
Closing in favor of https://github.com/VEuPathDB/web-eda/pull/1349

2022-09-09 21:08 UTC, closed without merging