FSM: Least ancestral entity logic
VEuPathDB/web-eda pull request #1492
Opened 2022-11-23 00:38 UTC by bobular

Fixes #1491

2022-12-13 17:46 UTC, dmfalke reviewed
Is there any concern when the entities are siblings? It looks like we will end up preferring the xaxis variable, in that case.

2022-12-13 23:58 UTC, bobular commented
Sorry about the assignment mix-up, and thanks for the review.

That's a great question about sibling entities.

We'd have to imagine a hypothetical entity diagram, like below.  Collection site is asterisked because it is the "geo-entity".
```
        collection site* - collection - sample
study < 
        publication
```

I think we have been assuming that the x-axis variable's entity and the geo-entity lie on the same branch. In fact the map overlay plugin's constraints specify this too: https://github.com/VEuPathDB/EdaDataService/blob/master/src/main/java/org/veupathdb/service/eda/ds/plugin/pass/MapMarkersOverlayPlugin.java#L52

In the regular map viz, we pass these constraints (`pieConstraints` and `pieDependencyOrder`) to the `InputVariables` component.

In the FSM it seems that we don't, and this needs to be fixed (by me!) - I can make a ticket tomorrow, or maybe we can include it in this issue+PR?

So when that is done, we'll have a situation where sibling entities should never be compared with the `leastAncestralEntity` function, but it will be implied rather than explicit in the code.  Would comments be sufficient in this case?

2022-12-14 04:50 UTC, dmfalke commented
A comment is probably adequate, although it wouldn't hurt to check and throw an error if the entities are not on the same branch. I'll leave that up to you :smile:

2023-01-11 15:40 UTC, bobular commented
Hi @dmfalke - not urgent but I've added a sanity check as suggested.

2023-02-16 13:12 UTC, dmfalke approved these changes

2023-02-16 13:44 UTC, dmfalke requested changes
Sorry, just caught something

2023-02-16 13:44 UTC, dmfalke commented on src/lib/core/utils/data-element-constraints.ts
> +      throw 'Error: variables not expected to be in different branches of entity diagram';
I just noticed this. You should throw an instance of an Error object, eg `throw new Error(message)`

2023-03-01 21:37 UTC, bobular commented
Impossible to test this "in anger" until we have a study where the geo-entity isn't the root.
The PopBio megastudy will be that soon.
Should we wait until we can test before merging?

2023-03-03 13:49 UTC, dmfalke commented
How do you feel about writing some unit tests for this?

2023-03-03 19:56 UTC, bobular commented
I feel that that would be the right thing to do in the circumstances.

2023-03-03 22:54 UTC, dmfalke commented
Not that I'm aware of. I think we can get away with entities with no variables here, so maybe it wouldn't be too hard to create some simple test data?

2023-03-17 23:35 UTC, bobular commented
Dave and I decided to test this with data rather than unit tests (jest/babel saga will wait until after monorepo)

feature site is back online - but map-markers is hanging, but I can confirm that the output entity logic is working because the entity-related errors that you see on feature.vectorbase.org mega-study when selecting **Study name** as the overlay variable, do not appear on my dev site (using feature site services).

So I'm going to merge!

2023-03-17 23:37 UTC, merged