changing the behavior of starred variables at MyVariable
VEuPathDB/web-eda pull request #200
Opened 2021-07-02 03:24 UTC by moontrip

when unstarring a variable at MyVariable, keep it visible

Here is an example  screenshot

![myvariable1](https://user-images.githubusercontent.com/12802305/124216087-669d6100-dac3-11eb-9d5d-78a2a0af6ecc.png)

2021-07-02 19:11 UTC, jtlong3rd requested changes
The new functionality is very nice, and your overall approach (maintain the visible starred variables in component state) is solid!

I have a few inline suggestions for simplifying the implementation and handling some linter warnings.

I also have a suggestion for a UX edge case, which GitHub won't let me describe in an inline comment because the relevant code is "too far away" from your diff. Currently, if "My Variables" is turned on, and you unstar every variable, "My Variables" is automatically turned off. This could be unpleasant for a user who accidentally unstars their last starred variable.

If you agree, you can make the following change: replace this block of code...

```typescript
  const starredVariableToggleDisabled = starredVariablesSet.size === 0;

  useEffect(() => {
    if (starredVariableToggleDisabled) {
      setShowOnlyStarredVariables(false);
    }
  }, [starredVariableToggleDisabled]);
```

... with this block of code:

```typescript
  const starredVariableToggleDisabled = (
    !showOnlyStarredVariables &&
    starredVariablesSet.size === 0
  );
```

(That is, (1) update the definition of `starredVariableToggleDisabled` so that the toggle is disabled when "My Variables" is turned off and there are no starred variables, and (2) delete the effect which was automatically turning off "My Variables" when there were no starred variables.)

2021-07-03 03:07 UTC, moontrip commented
@jtlong3rd sorry for late response. I am working for other project on every Friday so I didn't have time to look at your comments/suggestions carefully. In summary, I accepted all of your comments.

Some notes are left in the following. First of all, yes I knew that the toggle switch was turned off when all starred variables were removed at MyVariable. Since there was no specific requirement for that behavior, I just left it as was :) But I agree with your opinion that it is better to follow the basic approach, keep it visible. As for typing useState, I often defined types at useState so your comment is reasonable. Finally, I missed that approach to use toggleShowOnlyStarredVariables callback instead of using useEffect twice, which is much more elegant solution than mine. Thank you for suggesting better approach 👍👍

2021-07-03 22:28 UTC, jtlong3rd approved these changes

2021-07-06 16:13 UTC, dmfalke approved these changes

2021-07-06 16:16 UTC, merged