Variable tree updates
VEuPathDB/web-eda pull request #216
Opened 2021-07-08 17:03 UTC by dmfalke

This PR incorporates new variable metadata into the `VariableTree` component. It also includes some CSS updates for the scroll-able section of the variable tree, and an improvement to `io-ts` validation error messages.

closes #196 
closes #194

2021-07-08 17:22 UTC, dmfalke commented
I also tweaked the variable constraints tooltip that has been annoying. I added a delay for when it shows up. Hopefully it will not get in the way as much.

2021-07-08 17:41 UTC, jtlong3rd requested changes
Except for one "business-as-usual" inline suggestion, looks good!

2021-07-08 17:41 UTC, jtlong3rd commented on src/lib/core/components/VariableList.tsx
> +                    <li>
Missing "key"

2021-07-08 17:43 UTC, dmfalke commented on src/lib/core/components/VariableList.tsx
> +                    <li>
Ugh, thanks!

2021-07-08 17:46 UTC, jtlong3rd approved these changes

2021-07-12 11:36 UTC, bobular approved these changes
Have tested (including search-by-variable/vocabulary-value) and it all works nicely.  I skimmed the code and don't see any issues.

Some questions for future: what about real-estate if there are 25 featured variables? Or are they always single-digits?

2021-07-12 14:39 UTC, dmfalke commented
I hadn't thought about real estate for that many features vars. It's a good question. We could make that section collapsible and scrollable as well. I'll go ahead and merge this and we can discuss.

2021-07-12 14:55 UTC, merged