dependentAxisLabel always Count in subset histogram
VEuPathDB/web-eda pull request #320
Opened 2021-08-19 19:14 UTC by asizemore

_Addresses issue #288_

Set the y axis label of the histogram in the subsetting tab to always read "Count". See attached image.

Tested locally with GEMS and PRISM2.

<img width="746" alt="Screen Shot 2021-08-19 at 2 56 26 PM" src="https://user-images.githubusercontent.com/11710234/130130042-8ffcd155-d24f-41d2-9d96-32150e6da088.png">

2021-08-20 03:25 UTC, dmfalke approved these changes
Looks great, @asizemore!

2021-08-24 13:54 UTC, dmfalke commented
Hi @bobular, would you mind quickly reviewing this? Thanks!

2021-08-24 16:32 UTC, bobular commented
On it!

2021-08-24 16:42 UTC, bobular requested changes
Looks good!

Although my emacs IDE does not highlight this (which is strange, because I think it should) - `entityName` is now an unused "variable" in `HistogramPlotWithControls` and there is now no need to pass `entityName` through into this component.  The `entityName` prop can be removed from this component.

2021-08-25 13:03 UTC, asizemore commented
Hi @bobular ! Thank you for the feedback! I found three instances of `entityName` and removed them all so that the component does not use it anymore. Let me know if there's anything else you see that I can fix!

2021-08-25 14:39 UTC, bobular approved these changes

2021-08-25 14:43 UTC, merged