Viz thumbnails
VEuPathDB/web-eda pull request #354
Opened 2021-08-31 03:58 UTC by dmfalke

This PR adds support for using an image in the visualizations grid view. It takes advantage of changes introduced in https://github.com/VEuPathDB/web-components/pull/201.

### Overview

- Added browserify loader to webpack config
- Updated AnalysisState to be more immutable-friendly
- Fixed some minor type issues
- Added thumbnail property to Visualization
- Removed `gridComponent` from `VisualizationType` and replaced with `thumbnail` in overview

### Remaining TODOs
- [ ] Delete thumbnails if subset changes

2021-08-31 14:31 UTC, moontrip commented
@dmfalke For your information, I have tested plot vizs and they mostly worked great! 👍 I found a bug at Scatter plot viz: it worked fine for the default Raw plot, but either Smoothed mean or Best fit line threw an error (Error compiling fragment shader). However, your recent commit resolved this bug so no error concerning thumbnails found yet 😄

2021-08-31 15:43 UTC, dmfalke commented
This s ready for review. There are a couple of remaining TODOs, which I will address before merging.

2021-08-31 16:21 UTC, moontrip approved these changes

2021-08-31 16:30 UTC, jtlong3rd approved these changes

2021-08-31 17:05 UTC, dmfalke commented
For the default image (when the client hasn't generated one yet), I was thinking we could use a grayscale version of the selector icon with the text **Preview not available** overlaid. Thoughts?

2021-08-31 17:06 UTC, jtlong3rd commented
> For the default image (when the client hasn't generated one yet), I was thinking we could use a grayscale version of the selector icon with the text **Preview not available** overlaid. Thoughts?
> 
> ETA: This will happen when the subset changes.

Makes sense to me!

2021-09-01 21:51 UTC, bobular requested changes
It's great and looks much better than the mini versions of the plots we had before.  I just noticed some dependencies to update the thumbnail when front-end-only controls are used.

However, it seems not backwards compatible with old saved analyses - the error below occurs when maximising an old visualization.  This isn't really a problem I guess?  It will be a pain to diagnose (check out `main` - make viz's, check out this branch, etc). 

```
Unhandled Rejection (Error): No DOM element with id 'plotly_plot_div_1' exists on the page.
toImage/<
src/plots/PlotlyPlot.tsx:234

  231 |   toImage: async (imageOpts: ToImgopts) => {
  232 |     await sharedImport.promise;
  233 |     await new Promise((resolve) => setTimeout(resolve, 0));
> 234 |     return toImage(plotId, imageOpts);
      | ^ 
  235 |   },
  236 | }));
  237 | 
```

2021-09-01 21:51 UTC, bobular commented on src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
> +  }, [data, updateThumbnail]);
Non-back-end controls need to be passed too
```suggestion
  }, [data, updateThumbnail, dependentAxisLogScale]);
```

2021-09-01 21:51 UTC, bobular commented on src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
> +  }, [updateThumbnail, data]);
```suggestion
  }, [updateThumbnail, data, histogramProps.dependentAxisLogScale]);
```

2021-09-02 19:37 UTC, dmfalke commented
@bobular I've applied your suggestions. Thanks!

2021-09-02 19:40 UTC, bobular approved these changes

2021-09-02 19:41 UTC, merged