Chips
VEuPathDB/web-eda pull request #36
Opened 2021-04-06 15:14 UTC by chowington

2021-04-06 17:05 UTC, dmfalke requested changes
This is looking really good. See my suggestions inline.

2021-04-06 17:05 UTC, dmfalke commented on src/lib/core/components/FilterChipList.tsx
> +              </VariableLink>
Try passing the `VariableLink` element to the `text` prop. This should address the issue of the page reloading when clicking the delete button. You will probably need to modify the link text color.
```suggestion
                <FilterChip
                  text={(
                    <VariableLink
                      entityId={entity.id}
                      variableId={variable.id}
                      replace={true}
                      key={`filter-chip-${entity.id}-${variable.id}`}
                  >
                    {variable.displayName}
                   </VariableLink>
                  )}
                  tooltipText={filterValueDisplay}
                  isActive={
                    entity.id === props.selectedEntityId &&
                    variable.id === props.selectedVariableId
                  }
                  // Remove this filter on click of X button
                  onDelete={() =>
                    props.sessionState.setFilters(
                      session.filters.filter((f) => f !== filter)
                    )
                  }
                />
```

2021-04-06 20:23 UTC, chowington commented on src/lib/core/components/FilterChip.tsx
> +  onClick?: () => void;
Nope!

2021-04-06 20:24 UTC, chowington commented on src/lib/core/components/FilterChip.tsx
> +  text: string;
Inner content is passed as a React node now 👍

2021-04-07 03:24 UTC, dmfalke approved these changes
This is looking really great.

I have sprung a concern about the highlight colors. Right now, the active chip color is the same as the active entity in the variable tree, while the inactive chip color is the same as the active variable in the variable tree. I wonder if the active chip should have the same highlighting as the active variable in the variable tree, and maybe the inactive chip can have a simple outline. I'm not confident about this, so maybe we can get some feedback from others.

2021-04-07 13:08 UTC, dmfalke commented
I'm going to merge this. We can address highlighting as a follow-up.

2021-04-07 13:08 UTC, merged